export const STORAGE_KEYS = {
  PROJECTS_INDEX: 'CLIPFRAME_PROJECTS_INDEX',
  PROJECT_PREFIX: 'CLIPFRAME_PROJECT_',
  LAST_OPENED_PROJECT: 'CLIPFRAME_LAST_OPENED_PROJECT',
  EDITOR_SETTINGS: 'CLIPFRAME_EDITOR_SETTINGS',
}
